/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ranbr
 */
public class Principal extends javax.swing.JFrame {
private MantenimientoAlumno ventanaAlumno;
private MantenimientoAula ventanaAula;
private MantenimientoCarrera ventanaCarrera;
private MantenimientoCurso ventanaCurso;
private MantenimientoFacultad ventanaFacultad;
private MantenimientoJornada ventanaJornada;
private MantenimientoMaestro ventanaMaestro;
private MantenimientoSeccion ventanaSeccion;
private MantenimientoSede ventanaSede;
private AsignacionCA ventanaAsignacion;
private AsignacionCM ventanaAsignacionM;
private Laboratorios ventanaLaboratorios;

 public static String BD = "jdbc:mysql://127.0.0.1:3306/siu";
 public static String Usuario = "root";
 public static String Contraseña = "";
     
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        ventanaP = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        Mfacultades = new javax.swing.JMenuItem();
        MMaestros = new javax.swing.JMenuItem();
        MAlumnos = new javax.swing.JMenuItem();
        MCarreras = new javax.swing.JMenuItem();
        MCursos = new javax.swing.JMenuItem();
        MSecciones = new javax.swing.JMenuItem();
        MSedes = new javax.swing.JMenuItem();
        MAulas = new javax.swing.JMenuItem();
        MJornadas = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rachel Barrios 9959-18-649");

        ventanaP.setBackground(new java.awt.Color(51, 51, 51));
        ventanaP.setName("Rachel Barrios 9959-18-649"); // NOI18N

        javax.swing.GroupLayout ventanaPLayout = new javax.swing.GroupLayout(ventanaP);
        ventanaP.setLayout(ventanaPLayout);
        ventanaPLayout.setHorizontalGroup(
            ventanaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );
        ventanaPLayout.setVerticalGroup(
            ventanaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );

        jMenu8.setText("Abrir");
        jMenuBar1.add(jMenu8);

        jMenu3.setText("Catalogos");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Procesos");

        jMenuItem13.setText("Asignacion cursos a Alumnos");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem13);

        jMenuItem1.setText("Asignacion cursis a Maestros");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem2.setText("Laboratorios");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Informes");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Herramientas");

        Mfacultades.setText("Mantenimiento Facultades");
        Mfacultades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MfacultadesActionPerformed(evt);
            }
        });
        jMenu6.add(Mfacultades);

        MMaestros.setText("Mantenimiento Maestros");
        MMaestros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMaestrosActionPerformed(evt);
            }
        });
        jMenu6.add(MMaestros);

        MAlumnos.setText("Mantenimiento Alumnos");
        MAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAlumnosActionPerformed(evt);
            }
        });
        jMenu6.add(MAlumnos);

        MCarreras.setText("Mantenimiento Carreras");
        MCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCarrerasActionPerformed(evt);
            }
        });
        jMenu6.add(MCarreras);

        MCursos.setText("Mantenimiento Cursos");
        MCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCursosActionPerformed(evt);
            }
        });
        jMenu6.add(MCursos);

        MSecciones.setText("Mantenimiento Secciones");
        MSecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSeccionesActionPerformed(evt);
            }
        });
        jMenu6.add(MSecciones);

        MSedes.setText("Mantenimiento Sedes");
        MSedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSedesActionPerformed(evt);
            }
        });
        jMenu6.add(MSedes);

        MAulas.setText("Mantenimiento Aulas");
        MAulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAulasActionPerformed(evt);
            }
        });
        jMenu6.add(MAulas);

        MJornadas.setText("Mantenimiento Jornada");
        MJornadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MJornadasActionPerformed(evt);
            }
        });
        jMenu6.add(MJornadas);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Ayuda");
        jMenuBar1.add(jMenu7);

        jMenu2.setText("Salir");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaP)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaP)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void MAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAlumnosActionPerformed
ventanaAlumno= new MantenimientoAlumno();
ventanaP.add(ventanaAlumno);
// TODO add your handling code here:
    }//GEN-LAST:event_MAlumnosActionPerformed

    private void MfacultadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MfacultadesActionPerformed
ventanaFacultad= new MantenimientoFacultad();
ventanaP.add(ventanaFacultad);
// TODO add your handling code here:
    }//GEN-LAST:event_MfacultadesActionPerformed

    private void MCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCarrerasActionPerformed
ventanaCarrera= new MantenimientoCarrera();
ventanaP.add(ventanaCarrera);
// TODO add your handling code here:
    }//GEN-LAST:event_MCarrerasActionPerformed

    private void MCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCursosActionPerformed
ventanaCurso= new MantenimientoCurso();
ventanaP.add(ventanaCurso);
// TODO add your handling code here:
    }//GEN-LAST:event_MCursosActionPerformed

    private void MSeccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSeccionesActionPerformed
ventanaSeccion= new MantenimientoSeccion();
ventanaP.add(ventanaSeccion);
// TODO add your handling code here:
    }//GEN-LAST:event_MSeccionesActionPerformed

    private void MSedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSedesActionPerformed
ventanaSede= new MantenimientoSede();
ventanaP.add(ventanaSede);
// TODO add your handling code here:
    }//GEN-LAST:event_MSedesActionPerformed

    private void MAulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAulasActionPerformed
ventanaAula= new MantenimientoAula();
ventanaP.add(ventanaAula);
// TODO add your handling code here:
    }//GEN-LAST:event_MAulasActionPerformed

    private void MJornadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MJornadasActionPerformed
ventanaJornada= new MantenimientoJornada();
ventanaP.add(ventanaJornada);
// TODO add your handling code here:
    }//GEN-LAST:event_MJornadasActionPerformed

    private void MMaestrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMaestrosActionPerformed
ventanaMaestro= new MantenimientoMaestro();
ventanaP.add(ventanaMaestro);
// TODO add your handling code here:
    }//GEN-LAST:event_MMaestrosActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
  ventanaAsignacion= new AsignacionCA();
ventanaP.add(ventanaAsignacion);      // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ventanaAsignacionM = new AsignacionCM();
        ventanaP.add(ventanaAsignacionM);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        ventanaLaboratorios = new Laboratorios();
        ventanaP.add(ventanaLaboratorios);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MAlumnos;
    private javax.swing.JMenuItem MAulas;
    private javax.swing.JMenuItem MCarreras;
    private javax.swing.JMenuItem MCursos;
    private javax.swing.JMenuItem MJornadas;
    private javax.swing.JMenuItem MMaestros;
    private javax.swing.JMenuItem MSecciones;
    private javax.swing.JMenuItem MSedes;
    private javax.swing.JMenuItem Mfacultades;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JDesktopPane ventanaP;
    // End of variables declaration//GEN-END:variables
}
