/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prototipo2p;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Brayan Cifuentes
 */
public class Asignacion_cursos_alumno extends javax.swing.JInternalFrame {

    /**
     * Creates new form Empleados
     */
    String BD = "jdbc:mysql://localhost/siu";
    String Usuario = "root";
    String Clave = "admin";
    
    
    public Asignacion_cursos_alumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txt_codigosede = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_codigocarrera = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_codigojornada = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_codigoseccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_aula = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_curso = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_carnet = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_notaasignacion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Asignación de Cursos Alumnos");
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Codigo Carrera:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        txt_codigosede.setBackground(new java.awt.Color(204, 255, 255));
        txt_codigosede.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_codigosede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigosedeActionPerformed(evt);
            }
        });
        getContentPane().add(txt_codigosede, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 111, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Codigo Sede:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        txt_codigocarrera.setBackground(new java.awt.Color(204, 255, 255));
        txt_codigocarrera.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_codigocarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigocarreraActionPerformed(evt);
            }
        });
        getContentPane().add(txt_codigocarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 111, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Codigo Jornada:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        txt_codigojornada.setBackground(new java.awt.Color(204, 255, 255));
        txt_codigojornada.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_codigojornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigojornadaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_codigojornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 111, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Ingresa el código de Asignacion: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        txt_buscar.setBackground(new java.awt.Color(204, 255, 255));
        txt_buscar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txt_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 520, 30));

        jButton4.setBackground(new java.awt.Color(141, 141, 208));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/busquedap.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 60, 40));

        jButton1.setBackground(new java.awt.Color(141, 141, 208));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardarp.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 60, 40));

        jButton2.setBackground(new java.awt.Color(141, 141, 208));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 60, 40));

        jButton3.setBackground(new java.awt.Color(141, 141, 208));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 60, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Codigo Seccion:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        txt_codigoseccion.setBackground(new java.awt.Color(204, 255, 255));
        txt_codigoseccion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_codigoseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigoseccionActionPerformed(evt);
            }
        });
        getContentPane().add(txt_codigoseccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 111, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Codigo Aula:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        txt_aula.setBackground(new java.awt.Color(204, 255, 255));
        txt_aula.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_aula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_aulaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_aula, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 111, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Codigo Curso:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        txt_curso.setBackground(new java.awt.Color(204, 255, 255));
        txt_curso.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cursoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_curso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 111, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Carnet Alumno:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        txt_carnet.setBackground(new java.awt.Color(204, 255, 255));
        txt_carnet.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_carnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_carnetActionPerformed(evt);
            }
        });
        getContentPane().add(txt_carnet, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 111, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Nota Asignacion:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        txt_notaasignacion.setBackground(new java.awt.Color(204, 255, 255));
        txt_notaasignacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_notaasignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_notaasignacionActionPerformed(evt);
            }
        });
        getContentPane().add(txt_notaasignacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 111, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoform.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-390, -320, 1000, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_codigosedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigosedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigosedeActionPerformed

    private void txt_codigocarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigocarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigocarreraActionPerformed

    private void txt_codigojornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigojornadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigojornadaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
//Codigo que permite consultar registros en la base de datos
        try {
            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);
            PreparedStatement pst = cn.prepareStatement("select * from asignacioncursosalumnos where codigo_carrera = ?");
            pst.setString(1, txt_buscar.getText().trim());

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txt_codigocarrera.setText(rs.getString("codigo_carrera"));
                txt_codigosede.setText(rs.getString("codigo_sede"));
                txt_codigojornada.setText(rs.getString("codigo_jornada"));
                txt_codigoseccion.setText(rs.getString("codigo_seccion"));
                txt_aula.setText(rs.getString("codigo_aula"));
                txt_curso.setText(rs.getString("codigo_curso"));
                txt_carnet.setText(rs.getString("carnet_alumno"));
                txt_notaasignacion.setText(rs.getString("nota_asignacioncursoalumnos"));

            } else {
                JOptionPane.showMessageDialog(null, "Alumno no registrado.");
            }

        } catch (Exception e) {

        }                                
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//Codigo que permite insertar registros en al base de datos
        try {
            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);
            PreparedStatement pst = cn.prepareStatement("insert into asignacioncursosalumnos values(?,?,?,?,?,?,?,?)");

            pst.setString(1, txt_codigocarrera.getText().trim());
            pst.setString(2, txt_codigosede.getText().trim());
            pst.setString(3, txt_codigojornada.getText().trim());
            pst.setString(4, txt_codigoseccion.getText().trim());
            pst.setString(5, txt_aula.getText().trim());
            pst.setString(6, txt_curso.getText().trim());
            pst.setString(7, txt_carnet.getText().trim());
            pst.setString(8, txt_notaasignacion.getText().trim());

            pst.executeUpdate();

            txt_codigocarrera.setText("");
            txt_codigosede.setText("");
            txt_codigojornada.setText("");
            txt_codigoseccion.setText("");
            txt_aula.setText("");
            txt_curso.setText("");
            txt_carnet.setText("");
            txt_notaasignacion.setText("");

             JOptionPane.showMessageDialog(this, "¡REGISTRO EXITOSO!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
 JOptionPane.showMessageDialog(this, "¡Error en registro!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }                  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//Codigo que permite modificar registros en la base de datos
        try {
            String ID = txt_buscar.getText().trim();

            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);
            PreparedStatement pst = cn.prepareStatement("update asignacioncursosalumnos set codigo_carrera= ?, codigo_sede=?, codigo_jornada=?, codigo_seccion=?, codigo_aula=?, codigo_curso=?, carnet_alumno=?, nota_asignacioncursoalumnos=? where codigo_carrera = " + ID);

            pst.setString(1, txt_codigocarrera.getText().trim());
            pst.setString(2, txt_codigosede.getText().trim());
            pst.setString(3, txt_codigojornada.getText().trim());
            pst.setString(4, txt_codigoseccion.getText().trim());
            pst.setString(5, txt_aula.getText().trim());
            pst.setString(6, txt_curso.getText().trim());
            pst.setString(7, txt_carnet.getText().trim());
            pst.setString(8, txt_notaasignacion.getText().trim());

   
            pst.executeUpdate();

            txt_codigocarrera.setText("");
            txt_codigosede.setText("");
            txt_codigojornada.setText("");
            txt_codigoseccion.setText("");
            txt_aula.setText("");
            txt_curso.setText("");
            txt_carnet.setText("");
            txt_notaasignacion.setText("");


             JOptionPane.showMessageDialog(this, "¡MODIFICACION EXITOSA!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Error en modificación", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }                              
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//Codigo que permite borrar registros en la base de datos
        try {

            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);
            PreparedStatement pst = cn.prepareStatement("delete from asignacioncursosalumnos where codigo_carrera = ?");

            pst.setString(1, txt_buscar.getText().trim());
            pst.executeUpdate();

            txt_codigocarrera.setText("");
            txt_codigosede.setText("");
            txt_codigojornada.setText("");
            txt_codigoseccion.setText("");
            txt_aula.setText("");
            txt_curso.setText("");
            txt_carnet.setText("");
            txt_notaasignacion.setText("");
            

             JOptionPane.showMessageDialog(this, "¡ELIMINACION EXITOSA!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Error en eliminación", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }          
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_codigoseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigoseccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoseccionActionPerformed

    private void txt_aulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_aulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_aulaActionPerformed

    private void txt_cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cursoActionPerformed

    private void txt_carnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_carnetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_carnetActionPerformed

    private void txt_notaasignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_notaasignacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_notaasignacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_aula;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_carnet;
    private javax.swing.JTextField txt_codigocarrera;
    private javax.swing.JTextField txt_codigojornada;
    private javax.swing.JTextField txt_codigoseccion;
    private javax.swing.JTextField txt_codigosede;
    private javax.swing.JTextField txt_curso;
    private javax.swing.JTextField txt_notaasignacion;
    // End of variables declaration//GEN-END:variables
}
